### ISSUE TITLE
Opening Dataset Issue

### ISSUE THREAD

**Issue by emcyroyale** [deepmind/streetlearn#8]
I just received the dataset as a tar.gz file. It contains five text files for nyc and pittsburgh. I was expecting a leveldb file format of some kind.

When attempting to run using:
bazel run streetlearn/python/ui:human_agent -- --dataset_path=/home/tthomas/dataset

I receive the following:
`
[streetlearn/engine/dataset.cc:37] Unable initialize dataset: Invalid argument: /home/tthomas/streetlearn/: does not exist (create_if_missing is false)
Traceback (most recent call last):
  File "/home/tthomas/.cache/bazel/_bazel_tthomas/79f5987e2a8256f9256e161fa5f59745/execroot/org_deepmind_streetlearn/bazel-out/k8-fastbuild/bin/streetlearn/python/ui/human_agent.runfiles/org_deepmind_streetlearn/streetlearn/python/ui/human_agent.py", line 268, in <module>
    app.run(main)
  File "/work/backup_ignored_dir/ignored_my_programs/StreetLearnCanvas/local/lib/python2.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/work/backup_ignored_dir/ignored_my_programs/StreetLearnCanvas/local/lib/python2.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/tthomas/.cache/bazel/_bazel_tthomas/79f5987e2a8256f9256e161fa5f59745/execroot/org_deepmind_streetlearn/bazel-out/k8-fastbuild/bin/streetlearn/python/ui/human_agent.runfiles/org_deepmind_streetlearn/streetlearn/python/ui/human_agent.py", line 245, in main
    env = streetlearn.StreetLearn(FLAGS.dataset_path, config, game)
  File "/home/tthomas/.cache/bazel/_bazel_tthomas/79f5987e2a8256f9256e161fa5f59745/execroot/org_deepmind_streetlearn/bazel-out/k8-fastbuild/bin/streetlearn/python/ui/human_agent.runfiles/org_deepmind_streetlearn/streetlearn/python/environment/streetlearn.py", line 149, in __init__
    assert self._engine, "Could not initialise engine from %r." % dataset_path
AssertionError: Could not initialise engine from '/home/tthomas/streetlearn/dataset'.
`

I tried changing the path to point to the specific text file, to the tar.gz and the containing folder, but I get the same issue.

Any help?

**Comment by emcyroyale** [comment]
Hey Piotr,

I have the above mentioned dataset files. I am able to run both the human agent and oracle agent now. Looks like everything is working as expected now.

Thanks!

**Comment by SJTU-MKH** [comment]
Could you share the link of the dataset?
